/*

 GAMESPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 92

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GameSpritesBank 0

/* Super Gameboy palette 0 */
#define GameSpritesSGBPal0c0 6076
#define GameSpritesSGBPal0c1 8935
#define GameSpritesSGBPal0c2 6596
#define GameSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define GameSpritesSGBPal1c0 6076
#define GameSpritesSGBPal1c1 8935
#define GameSpritesSGBPal1c2 6596
#define GameSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define GameSpritesSGBPal2c0 6076
#define GameSpritesSGBPal2c1 8935
#define GameSpritesSGBPal2c2 6596
#define GameSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define GameSpritesSGBPal3c0 6076
#define GameSpritesSGBPal3c1 8935
#define GameSpritesSGBPal3c2 6596
#define GameSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define GameSpritesCGBPal0c0 6076
#define GameSpritesCGBPal0c1 8935
#define GameSpritesCGBPal0c2 6596
#define GameSpritesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define GameSpritesCGBPal1c0 6076
#define GameSpritesCGBPal1c1 15070
#define GameSpritesCGBPal1c2 351
#define GameSpritesCGBPal1c3 33

/* Gameboy Color palette 2 */
#define GameSpritesCGBPal2c0 29791
#define GameSpritesCGBPal2c1 30718
#define GameSpritesCGBPal2c2 7167
#define GameSpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define GameSpritesCGBPal3c0 1290
#define GameSpritesCGBPal3c1 12310
#define GameSpritesCGBPal3c2 30174
#define GameSpritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define GameSpritesCGBPal4c0 6076
#define GameSpritesCGBPal4c1 32767
#define GameSpritesCGBPal4c2 2559
#define GameSpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define GameSpritesCGBPal5c0 22976
#define GameSpritesCGBPal5c1 12287
#define GameSpritesCGBPal5c2 32166
#define GameSpritesCGBPal5c3 30718

/* Gameboy Color palette 6 */
#define GameSpritesCGBPal6c0 6076
#define GameSpritesCGBPal6c1 23454
#define GameSpritesCGBPal6c2 273
#define GameSpritesCGBPal6c3 32

/* Gameboy Color palette 7 */
#define GameSpritesCGBPal7c0 28895
#define GameSpritesCGBPal7c1 31542
#define GameSpritesCGBPal7c2 28636
#define GameSpritesCGBPal7c3 33
/* CGBpalette entries. */
extern unsigned char GameSpritesCGB[];
/* Start of tile array. */
extern unsigned char GameSprites[];

/* End of GAMESPRITES.H */
