/*

 MAPTILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define MapTileSetBank 0

/* Super Gameboy palette 0 */
#define MapTileSetSGBPal0c0 6076
#define MapTileSetSGBPal0c1 8935
#define MapTileSetSGBPal0c2 6596
#define MapTileSetSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MapTileSetSGBPal1c0 6076
#define MapTileSetSGBPal1c1 8935
#define MapTileSetSGBPal1c2 6596
#define MapTileSetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MapTileSetSGBPal2c0 6076
#define MapTileSetSGBPal2c1 8935
#define MapTileSetSGBPal2c2 6596
#define MapTileSetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MapTileSetSGBPal3c0 6076
#define MapTileSetSGBPal3c1 8935
#define MapTileSetSGBPal3c2 6596
#define MapTileSetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MapTileSetCGBPal0c0 32166
#define MapTileSetCGBPal0c1 26944
#define MapTileSetCGBPal0c2 26848
#define MapTileSetCGBPal0c3 14433

/* Gameboy Color palette 1 */
#define MapTileSetCGBPal1c0 6076
#define MapTileSetCGBPal1c1 4609
#define MapTileSetCGBPal1c2 10560
#define MapTileSetCGBPal1c3 10240

/* Gameboy Color palette 2 */
#define MapTileSetCGBPal2c0 9855
#define MapTileSetCGBPal2c1 8935
#define MapTileSetCGBPal2c2 5249
#define MapTileSetCGBPal2c3 10240

/* Gameboy Color palette 3 */
#define MapTileSetCGBPal3c0 31409
#define MapTileSetCGBPal3c1 8832
#define MapTileSetCGBPal3c2 10570
#define MapTileSetCGBPal3c3 1291

/* Gameboy Color palette 4 */
#define MapTileSetCGBPal4c0 31409
#define MapTileSetCGBPal4c1 433
#define MapTileSetCGBPal4c2 13632
#define MapTileSetCGBPal4c3 99

/* Gameboy Color palette 5 */
#define MapTileSetCGBPal5c0 31409
#define MapTileSetCGBPal5c1 21140
#define MapTileSetCGBPal5c2 5296
#define MapTileSetCGBPal5c3 0

/* Gameboy Color palette 6 */
#define MapTileSetCGBPal6c0 31409
#define MapTileSetCGBPal6c1 29596
#define MapTileSetCGBPal6c2 25
#define MapTileSetCGBPal6c3 0

/* Gameboy Color palette 7 */
#define MapTileSetCGBPal7c0 31409
#define MapTileSetCGBPal7c1 8832
#define MapTileSetCGBPal7c2 1259
#define MapTileSetCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char MapTileSetCGB[];
/* Start of tile array. */
extern unsigned char MapTileSet[];

/* End of MAPTILESET.H */
