/*

 SPLASHSCREENTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 74

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SplashScreenTilesBank 0

/* Super Gameboy palette 0 */
#define SplashScreenTilesSGBPal0c0 6076
#define SplashScreenTilesSGBPal0c1 8935
#define SplashScreenTilesSGBPal0c2 6596
#define SplashScreenTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SplashScreenTilesSGBPal1c0 6076
#define SplashScreenTilesSGBPal1c1 8935
#define SplashScreenTilesSGBPal1c2 6596
#define SplashScreenTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SplashScreenTilesSGBPal2c0 6076
#define SplashScreenTilesSGBPal2c1 8935
#define SplashScreenTilesSGBPal2c2 6596
#define SplashScreenTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SplashScreenTilesSGBPal3c0 6076
#define SplashScreenTilesSGBPal3c1 8935
#define SplashScreenTilesSGBPal3c2 6596
#define SplashScreenTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SplashScreenTilesCGBPal0c0 32201
#define SplashScreenTilesCGBPal0c1 32201
#define SplashScreenTilesCGBPal0c2 32163
#define SplashScreenTilesCGBPal0c3 32002

/* Gameboy Color palette 1 */
#define SplashScreenTilesCGBPal1c0 29662
#define SplashScreenTilesCGBPal1c1 4609
#define SplashScreenTilesCGBPal1c2 8353
#define SplashScreenTilesCGBPal1c3 5120

/* Gameboy Color palette 2 */
#define SplashScreenTilesCGBPal2c0 9855
#define SplashScreenTilesCGBPal2c1 8935
#define SplashScreenTilesCGBPal2c2 5249
#define SplashScreenTilesCGBPal2c3 5120

/* Gameboy Color palette 3 */
#define SplashScreenTilesCGBPal3c0 31409
#define SplashScreenTilesCGBPal3c1 30717
#define SplashScreenTilesCGBPal3c2 31
#define SplashScreenTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define SplashScreenTilesCGBPal4c0 31409
#define SplashScreenTilesCGBPal4c1 433
#define SplashScreenTilesCGBPal4c2 13632
#define SplashScreenTilesCGBPal4c3 99

/* Gameboy Color palette 5 */
#define SplashScreenTilesCGBPal5c0 31409
#define SplashScreenTilesCGBPal5c1 21140
#define SplashScreenTilesCGBPal5c2 5296
#define SplashScreenTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define SplashScreenTilesCGBPal6c0 31409
#define SplashScreenTilesCGBPal6c1 29596
#define SplashScreenTilesCGBPal6c2 25
#define SplashScreenTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define SplashScreenTilesCGBPal7c0 6076
#define SplashScreenTilesCGBPal7c1 8935
#define SplashScreenTilesCGBPal7c2 6596
#define SplashScreenTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char SplashScreenTilesCGB[];
/* Start of tile array. */
extern unsigned char SplashScreenTiles[];

/* End of SPLASHSCREENTILES.H */
