/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : mapTileSet.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundWidth 20
#define BackgroundHeight 18
#define BackgroundBank 0

#define Background BackgroundPLN0
extern unsigned char BackgroundPLN0[];
extern unsigned char BackgroundPLN1[];

/* End of BACKGROUND.H */
