/*

 BG_HIGHSCORES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : G:\GameboyProjects\Fishin' Hole\Tileset_editor_data\mapTileSet.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BG_HighScoresWidth 20
#define BG_HighScoresHeight 18
#define BG_HighScoresBank 1

#define BG_HighScores BG_HighScoresPLN0
extern unsigned char BG_HighScoresPLN0[];
extern unsigned char BG_HighScoresPLN1[];

/* End of BG_HIGHSCORES.H */
