/*

 BG_STARTMENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : mapTileSet.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BG_StartMenuWidth 20
#define BG_StartMenuHeight 18
#define BG_StartMenuBank 0

#define BG_StartMenu BG_StartMenuPLN0
extern const unsigned char BG_StartMenuPLN0[];
extern const unsigned char BG_StartMenuPLN1[];

/* End of BG_STARTMENU.H */
