/*

 BG_SPLASHSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : splashScreen.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BG_SplashScreenWidth 20
#define BG_SplashScreenHeight 18
#define BG_SplashScreenBank 0

#define BG_SplashScreen BG_SplashScreenPLN0
extern unsigned char BG_SplashScreenPLN0[];
extern unsigned char BG_SplashScreenPLN1[];

/* End of BG_SPLASHSCREEN.H */
