/*

 BG_SUBGAMES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : mapTileSet.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BG_SubGamesWidth 20
#define BG_SubGamesHeight 18
#define BG_SubGamesBank 0

#define BG_SubGames BG_SubGamesPLN0
extern const unsigned char BG_SubGamesPLN0[];
extern const unsigned char BG_SubGamesPLN1[];

/* End of BG_SUBGAMES.H */
